#!/bin/sh
SCRIPT_DIR=$(CDPATH="" cd -- "$(dirname -- "$0")" && pwd)
session_type=$(echo "${XDG_SESSION_TYPE}" | tr '[:upper:]' '[:lower:]')

session_override=""

for arg in "$@"; do
	case "$arg" in
		--x11)
			session_override="x11"
			;;
		--wayland)
			session_override="wayland"
			;;
	esac
done

if [ -n "$session_override" ]; then
	session_type="$session_override"
fi

case "$session_type" in
	x11)
		echo "Running SGLogout - x11"
		exec "$SCRIPT_DIR/sglogout-x11" "$@"
		;;
	wayland)
		echo "Running SGLogout - Wayland"
		exec "$SCRIPT_DIR/sglogout-wayland" "$@"
		;;
	*)
		echo "Unsupported or unknown session type: '$session_type', assuming Wayland" >&2
		exec "$SCRIPT_DIR/sglogout-wayland" "$@"
		;;
esac
